#!/usr/bin/env bash
set -e
set -o pipefail
unset D_DEBUG
ARGS=""

while getopts ":-:" option; do
  case "${option}" in
    -)
        # echo "OPTARG: ${OPTARG}"
        case "${OPTARG}" in
            "go")
                IGO=true
                echo "Enabling go"
                ;;
            "aws")
                IAWS=true
                echo "Enabling aws"
                ;;
            "tf")
                ITF=true
                echo "Enabling terraform"
                ;;
            "docker")
                IDOCKER=true
                echo "Enabling docker"
                ;;
            "code")
                ICODESERVER=true
                echo "Enabling code server"
                ;;
            "d")
                D_DEBUG=true
                echo "Enabling debug"
                ;;
            "test")
                echo -n "$*"
                exit 0
                ;;
            *)
                echo "Usage: $0 [-go] [-aws] [-tf] [-docker] [-code] [--d] [-test]"
                exit 1
                ;;
        esac
        ;;
    *)
      echo "Usage: $0 [-go] [-aws] [-tf] [-docker] [-code] [--d] [-test]"
      exit 1
      ;;
  esac
done

source scripts/functions
source scripts/shell_inc
unset_d

BASEDIR=$(dirname $0)
cd $BASEDIR

echo "Starting install"
echo "Running check_prereqs"
check_prereqs
case "${D_OS}" in
    linux*)
        echo "Installing for Linux using apt and Homebrew"
        source scripts/linux/functions
        source scripts/linux/shell_inc
        installLinux
        ;;
    macos*)
        echo "Installing for MacOS using HomeBrew"
        source scripts/macos/functions
        source scripts/macos/shell_inc
        installMacOS
        ;;
    *)
        echo "Unknown operating system"
        exit 1
        ;;
esac
# [[ $D_ZSH == "true" && $D_SHELL == "zsh" ]] && install_zsh_inc || install_bash_inc
# [[ $D_ZSH == "true" && $D_SHELL == "zsh" ]] && install_zsh_rc || install_bash_rc
# [[ $D_ZSH == "true" && $D_SHELL == "zsh" ]] && echo "zsh: $D_SHELL" || echo "bash: $D_SHELL"

# [[ $IGO == true ]] && install_go || true
# [[ $IGO == true ]] && install_go_tools || true
# [[ $IAWS == true ]] && install_aws || true
# [[ $ITF == true ]] && install_terraform || true
# [[ $IDOCKER = true ]] && install_docker || true
# [[ $IDC == true ]] && install_docker_compose || true
# [[ $ICODESERVER = true ]] && install_code_server || true


# ln -s ${PWD}/terraformrc ~/.terraformrc

[[ $D_DEBUG == "true" ]] && debug_output || true










