#!/usr/bin/env bash
set -e
set -o errexit
set -o nounset
set -o pipefail
D_DEBUG=false
ARGS=${1:-none}
[[ ${ARGS} == "-d" ]] && export D_DEBUG=true || true
source scripts/functions
source bash_inc
unset_d

BASEDIR=$(dirname $0)
cd $BASEDIR

echo "Starting script"
echo "Running check_prereqs"
check_prereqs
install_bash_inc
install_bash_rc
checkVersions
[[ $IGO == true ]] && install_go || true
install_go_tools
install_aws
install_terraform


ln -s ${PWD}/terraformrc ~/.terraformrc











